const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS';
const GET_ALL_CONTACTS_FAILED = 'GET_ALL_CONTACTS_FAILED';
const GET_ALL_CONTACTS_SUCCESS = 'GET_ALL_CONTACTS_SUCCESS';

export {
  GET_ALL_CONTACTS,
  GET_ALL_CONTACTS_FAILED,
  GET_ALL_CONTACTS_SUCCESS,
};
