const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS';
const GET_ALL_CONTACTS_FAILED = 'GET_ALL_CONTACTS_FAILED';
const GET_ALL_CONTACTS_SUCCESS = 'GET_ALL_CONTACTS_SUCCESS';

const SAVE_CONTACT = 'SAVE_CONTACT';
const SAVE_CONTACT_FAILED = 'SAVE_CONTACT_FAILED';
const SAVE_CONTACT_SUCCESS = 'SAVE_CONTACT_SUCCESS';

const GET_CONTACT_DETAILS = 'GET_CONTACT_DETAILS';
const GET_CONTACT_DETAILS_FAILED = 'GET_CONTACT_DETAILS_FAILED';
const GET_CONTACT_DETAILS_SUCCESS = 'GET_CONTACT_DETAILS_SUCCESS';

const EDIT_CONTACT = 'EDIT_CONTACT';
const EDIT_CONTACT_FAILED = 'EDIT_CONTACT_FAILED';
const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS';

const DELETE_CONTACT = 'DELETE_CONTACT';
const DELETE_CONTACT_FAILED = 'DELETE_CONTACT_FAILED';
const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';

export {
  GET_ALL_CONTACTS,
  GET_ALL_CONTACTS_FAILED,
  GET_ALL_CONTACTS_SUCCESS,
  SAVE_CONTACT,
  SAVE_CONTACT_FAILED,
  SAVE_CONTACT_SUCCESS,
  GET_CONTACT_DETAILS,
  GET_CONTACT_DETAILS_FAILED,
  GET_CONTACT_DETAILS_SUCCESS,
  EDIT_CONTACT,
  EDIT_CONTACT_FAILED,
  EDIT_CONTACT_SUCCESS,
  DELETE_CONTACT,
  DELETE_CONTACT_FAILED,
  DELETE_CONTACT_SUCCESS,
};
