const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS';
const GET_ALL_CONTACTS_FAILED = 'GET_ALL_CONTACTS_FAILED';
const GET_ALL_CONTACTS_SUCCESS = 'GET_ALL_CONTACTS_SUCCESS';

const SAVE_CONTACT = 'SAVE_CONTACT';
const SAVE_CONTACT_FAILED = 'SAVE_CONTACT_FAILED';
const SAVE_CONTACT_SUCCESS = 'SAVE_CONTACT_SUCCESS';

export {
  GET_ALL_CONTACTS,
  GET_ALL_CONTACTS_FAILED,
  GET_ALL_CONTACTS_SUCCESS,
  SAVE_CONTACT,
  SAVE_CONTACT_FAILED,
  SAVE_CONTACT_SUCCESS,
};
